### PR TITLE
Updated blui dependencies of mui v5

### LINKED ISSUE #40: Upgrade to using MUI v5
#### Describe the desired behavior
Update library to use the latest MUI v5 (@mui/material)
#### Describe the current behavior
We are using the old version 4.x
#### Is this request related to a current issue?
No

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes #40

#### Changes proposed in this Pull Request:
- Updated brightlayer UI dependencies for mui v5

#### To Test:
- yarn start

### CODE REVIEW

**Comment by ektasawant** [comment]
Are we going to update react, react-dom, react-router-dom versions in this PR ?

**Comment by jeffvg** [comment]
I know we all talked about some performance issues after upgrades but this seems odd.

https://user-images.githubusercontent.com/37150565/162473993-1f8aa7d3-0257-4704-bb3d-1b27875874c8.mov

**Comment by bkarambe** [comment]
> after doing yarn && yarn start, this is kicked up..
> 
> image

This issue exists in the base mui-v5 branch and is known issue https://github.com/brightlayer-ui/react-themes/pull/33#issuecomment-1074042670.

**Comment by bkarambe** [comment]
> Are we going to update react, react-dom, react-router-dom versions in this PR ?

I think we should cover react, react-dom and react-router-dom in separate ticket, as there will be more structural changes.

**Comment by bkarambe** [comment]
> I know we all talked about some performance issues after upgrades but this seems odd.
> 
>  react-showcase.mov

I don't see this much lag in this branch.

https://user-images.githubusercontent.com/25982779/162713280-774165db-2477-421f-92b1-c0ab7a171c52.mov

**Comment by jeffvg** [comment]
> > I know we all talked about some performance issues after upgrades but this seems odd.
> > react-showcase.mov
> 
> I don't see this much lag in this branch.
> 
>  Screen.Recording.2022-04-11.at.3.16.55.PM.mov

@bkarambe I see less lag in the light theme than the dark theme for some reason. Can you try clicking around while in dark theme

**Comment by bkarambe** [comment]
> > > I know we all talked about some performance issues after upgrades but this seems odd.
> > > react-showcase.mov
> > 
> > 
> > I don't see this much lag in this branch.
> > Screen.Recording.2022-04-11.at.3.16.55.PM.mov
> 
> @bkarambe I see less lag in the light theme than the dark theme for some reason. Can you try clicking around while in dark theme

Yes I see it now. I tried debugging and found that it works well if we comment cacheRTL logic. @ektasawant Can you help us out here?

**Comment by ektasawant** [comment]
> > > > I know we all talked about some performance issues after upgrades but this seems odd.
> > > > react-showcase.mov
> > > 
> > > 
> > > I don't see this much lag in this branch.
> > > Screen.Recording.2022-04-11.at.3.16.55.PM.mov
> > 
> > 
> > @bkarambe I see less lag in the light theme than the dark theme for some reason. Can you try clicking around while in dark theme
> 
> Yes I see it now. I tried debugging and found that it works well if we comment cacheRTL logic. @ektasawant Can you help us out here?

After styled engine integration we can check it again. https://github.com/brightlayer-ui/react-showcase-demo/pull/54#pullrequestreview-914806635.

**Review by jeffvg — APPROVED** [review]
everything seems good except the performance. The recalculate will just cycle until we upgrade everything else.
image

**Review by daileytj — APPROVED** [review]

**Pull request merged**
