### PR TITLE
Feature/3135 list item tag style engine

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes # BLUI-3135

Changes proposed in this Pull Request:
Updated example to use style components or sx prop

To Test:
yarn start

### CODE REVIEW

**Comment by ektasawant** [comment]
This is not related to listItem tag but I observed infolistItem is not looking like previous versions.
Previous version
prev_InfolistItem

Current version

curr_InfolistItem

**Comment by bkarambe** [comment]
> This is not related to listItem tag but I observed infolistItem is not looking like previous versions. Previous version prev_InfolistItem
> 
> Current version
> 
> curr_InfolistItem

This issue is in the react-component-library, where padding-left and padding-right have been added to ListItemTag. I will create an issue for that.

**Comment by emclaug2** [comment]
image

Styles being overridden by MUI?

**Comment by ektasawant** [comment]
> > This is not related to listItem tag but I observed infolistItem is not looking like previous versions. Previous version prev_InfolistItem
> > Current version
> > curr_InfolistItem
> 
> I have checked with dev branch, and there is no difference. Here's the screenshot.
> 
> Screenshot 2022-05-19 at 6 16 46 PM

working fine on dev 👍

**Review by ektasawant — APPROVED** [review]

**Pull request merged**
